sudo: false
language: python
matrix:
  include:
  - python: 3.5
    env: TOX_ENV=py35
  - python: 3.6
    env: TOX_ENV=py36
  - python: 3.7
    env: TOX_ENV=py37
  - python: 3.8
    env: TOX_ENV=py38
  - python: 3.5
    env: TOX_ENV=quality
install:
- pip install -r requirements/travis.txt
script:
- tox -e $TOX_ENV
before_cache:
- rm -rf $HOME/.cache/pip/log
cache:
  directories:
  - "$HOME/.cache/pip"
deploy:
  provider: pypi
  user: edx
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: '3.5'
    condition: "$TOXENV = quality"
  password:
    secure: k8GGw+XjP9jIHRDjFkSe4vuHpBFxoVl2E4rWeXcCDyDncnQOGkR0I5I8XK4lEfs1Cx9Wz12cjkzIpTD7J4cO/Kguf7UOngAy1yAZytOuvS2JqUdsbI/TVVFf6mRS/+wz/yfzgFAr/8GCDWoLGat3PwZ3sE6vulK+y0dLlcmApVU50zYJTxyFEoNgMHiTTu95vaZ0+8H+KKUXjGKVp7MPpcH3ojMO/BiNpjP9cISW4D7Xpr3sgfhGXkMVuvnMVHRv5m76tCG5slRWRDuqpqHYdrOURQRAu2/Uit4I/QBVahFYt5FLL1eoJUAytcq7if4pJkeRolD6iqU0GIrSbPyyoUHLgitWswygj1x1KekJ3ICAR6/P7Ui6PJhrYhDzVZIh5TXaUZTS3VgNbBDkKLtaiyLlir7HTxkfMfJuvrx8VuCE1KtF9vQXr4zre5IDPV6ZePfrHiQOl1NXBRaDMKuDe2OKpgbfBl9XO+Nk3aSGpmcLgbCeR2CaweRMELn3W9AATVQyzOM40Nd+eVaNLy3yI4Iw21GFQ3UbGuis8CXIY/fn5SmR1BsD5IdtPYekgOq75siMPsyPjnbXvmwxnLAt1qUxUtLlsA77wqoJ11KB1JZMoBa6b1hFPK2AfRjz4EZxKas+a8Ku+QvMufh6Cqe1KlEsIVYS++KF9SW+05L6hDU=
